#!/usr/bin/env bash
# India arm. Generated by eval/india_windows.py from data/cache/manifest_iblend.json;
# one line per admissible (series, June) window. Run from demand-control/.
set -u
PY=../.venv/bin/python

# 1. the benchmark: five forecasters, identical calibration layer, every window
$PY eval/comparative.py --arms india --out comparative_india --skip-done

# 2. the horizon gap: train the quantile boosters per window, then measure open loop
[ -f models/IIITD_Academic@2015/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Academic --tag @2015 --train-start '2014-03-01 00:00:00' --train-end '2015-03-31 23:45' --valid-end '2015-05-31 23:45' --test-start '2015-06-01 00:00' --test-end '2015-06-30 23:45'
[ -f results/horizon_risk_IIITD_Academic@2015.json ] || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2015 --start '2015-06-01' --end '2015-06-30 23:45' --valid-start '2015-04-01' --valid-end '2015-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Academic@2016/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Academic --tag @2016 --train-start '2015-01-01 00:00:00' --train-end '2016-03-31 23:45' --valid-end '2016-05-31 23:45' --test-start '2016-06-01 00:00' --test-end '2016-06-30 23:45'
[ -f results/horizon_risk_IIITD_Academic@2016.json ] || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2016 --start '2016-06-01' --end '2016-06-30 23:45' --valid-start '2016-04-01' --valid-end '2016-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Academic@2017/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Academic --tag @2017 --train-start '2016-01-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Academic@2017.json ] || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2017 --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Library@2014/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Library --tag @2014 --train-start '2013-09-01 00:00:00' --train-end '2014-03-31 23:45' --valid-end '2014-05-31 23:45' --test-start '2014-06-01 00:00' --test-end '2014-06-30 23:45'
[ -f results/horizon_risk_IIITD_Library@2014.json ] || $PY eval/horizon_risk.py --building IIITD_Library --tag @2014 --start '2014-06-01' --end '2014-06-30 23:45' --valid-start '2014-04-01' --valid-end '2014-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Library@2016/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Library --tag @2016 --train-start '2015-09-01 00:00:00' --train-end '2016-03-31 23:45' --valid-end '2016-05-31 23:45' --test-start '2016-06-01 00:00' --test-end '2016-06-30 23:45'
[ -f results/horizon_risk_IIITD_Library@2016.json ] || $PY eval/horizon_risk.py --building IIITD_Library --tag @2016 --start '2016-06-01' --end '2016-06-30 23:45' --valid-start '2016-04-01' --valid-end '2016-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Dining@2017/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Dining --tag @2017 --train-start '2016-07-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Dining@2017.json ] || $PY eval/horizon_risk.py --building IIITD_Dining --tag @2017 --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Facilities@2015/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Facilities --tag @2015 --train-start '2014-06-01 00:00:00' --train-end '2015-03-31 23:45' --valid-end '2015-05-31 23:45' --test-start '2015-06-01 00:00' --test-end '2015-06-30 23:45'
[ -f results/horizon_risk_IIITD_Facilities@2015.json ] || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2015 --start '2015-06-01' --end '2015-06-30 23:45' --valid-start '2015-04-01' --valid-end '2015-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Facilities@2016/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Facilities --tag @2016 --train-start '2015-11-01 00:00:00' --train-end '2016-03-31 23:45' --valid-end '2016-05-31 23:45' --test-start '2016-06-01 00:00' --test-end '2016-06-30 23:45'
[ -f results/horizon_risk_IIITD_Facilities@2016.json ] || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2016 --start '2016-06-01' --end '2016-06-30 23:45' --valid-start '2016-04-01' --valid-end '2016-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Facilities@2017/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Facilities --tag @2017 --train-start '2016-01-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Facilities@2017.json ] || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2017 --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Boys@2014/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Boys --tag @2014 --train-start '2013-09-01 00:00:00' --train-end '2014-03-31 23:45' --valid-end '2014-05-31 23:45' --test-start '2014-06-01 00:00' --test-end '2014-06-30 23:45'
[ -f results/horizon_risk_IIITD_Boys@2014.json ] || $PY eval/horizon_risk.py --building IIITD_Boys --tag @2014 --start '2014-06-01' --end '2014-06-30 23:45' --valid-start '2014-04-01' --valid-end '2014-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Girls@2014/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Girls --tag @2014 --train-start '2013-10-01 00:00:00' --train-end '2014-03-31 23:45' --valid-end '2014-05-31 23:45' --test-start '2014-06-01 00:00' --test-end '2014-06-30 23:45'
[ -f results/horizon_risk_IIITD_Girls@2014.json ] || $PY eval/horizon_risk.py --building IIITD_Girls --tag @2014 --start '2014-06-01' --end '2014-06-30 23:45' --valid-start '2014-04-01' --valid-end '2014-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Girls@2017/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Girls --tag @2017 --train-start '2016-08-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Girls@2017.json ] || $PY eval/horizon_risk.py --building IIITD_Girls --tag @2017 --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Campus@2017/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Campus --tag @2017 --train-start '2016-08-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Campus@2017.json ] || $PY eval/horizon_risk.py --building IIITD_Campus --tag @2017 --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop

# 3. bootstrap intervals on every horizon row. A fresh run above writes them;
#    this attaches them to a result produced before they existed.
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Academic@2015.json || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2015 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Academic@2016.json || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2016 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Academic@2017.json || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2017 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Library@2014.json || $PY eval/horizon_risk.py --building IIITD_Library --tag @2014 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Library@2016.json || $PY eval/horizon_risk.py --building IIITD_Library --tag @2016 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Dining@2017.json || $PY eval/horizon_risk.py --building IIITD_Dining --tag @2017 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Facilities@2015.json || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2015 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Facilities@2016.json || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2016 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Facilities@2017.json || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2017 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Boys@2014.json || $PY eval/horizon_risk.py --building IIITD_Boys --tag @2014 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Girls@2014.json || $PY eval/horizon_risk.py --building IIITD_Girls --tag @2014 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Girls@2017.json || $PY eval/horizon_risk.py --building IIITD_Girls --tag @2017 --ci-only
grep -q empirical_horizon_ci results/horizon_risk_IIITD_Campus@2017.json || $PY eval/horizon_risk.py --building IIITD_Campus --tag @2017 --ci-only
echo "india arm done $(date)"
