#!/usr/bin/env bash
# The horizon windows again, with the adaptive-conformal step stated as a
# fraction (0.006) of the split-conformal interval width on the validation
# block instead of as an absolute number. Generated by eval/india_windows.py
# --gamma-rel. Run from demand-control/.
set -u
PY=../.venv/bin/python

# Fox at both steps: its original tensor is the benchmark harness's, so the
# pair has to come from this trainer for the comparison to be paired.
[ -f models/Fox_office_Gaylord@g/forecast_test.parquet ] || $PY forecast/train.py --buildings Fox_office_Gaylord --tag @g
[ -f results/horizon_risk_Fox_office_Gaylord@g.json ] || $PY eval/horizon_risk.py --building Fox_office_Gaylord --tag @g --skip-closed-loop
[ -f models/Fox_office_Gaylord@k/forecast_test.parquet ] || $PY forecast/train.py --buildings Fox_office_Gaylord --tag @k --adaptive-gamma-rel 0.006
[ -f results/horizon_risk_Fox_office_Gaylord@k.json ] || $PY eval/horizon_risk.py --building Fox_office_Gaylord --tag @k --skip-closed-loop

[ -f models/IIITD_Academic@2015k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Academic --tag @2015k --adaptive-gamma-rel 0.006 --train-start '2014-03-01 00:00:00' --train-end '2015-03-31 23:45' --valid-end '2015-05-31 23:45' --test-start '2015-06-01 00:00' --test-end '2015-06-30 23:45'
[ -f results/horizon_risk_IIITD_Academic@2015k.json ] || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2015k --start '2015-06-01' --end '2015-06-30 23:45' --valid-start '2015-04-01' --valid-end '2015-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Academic@2016k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Academic --tag @2016k --adaptive-gamma-rel 0.006 --train-start '2015-01-01 00:00:00' --train-end '2016-03-31 23:45' --valid-end '2016-05-31 23:45' --test-start '2016-06-01 00:00' --test-end '2016-06-30 23:45'
[ -f results/horizon_risk_IIITD_Academic@2016k.json ] || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2016k --start '2016-06-01' --end '2016-06-30 23:45' --valid-start '2016-04-01' --valid-end '2016-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Academic@2017k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Academic --tag @2017k --adaptive-gamma-rel 0.006 --train-start '2016-01-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Academic@2017k.json ] || $PY eval/horizon_risk.py --building IIITD_Academic --tag @2017k --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Library@2014k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Library --tag @2014k --adaptive-gamma-rel 0.006 --train-start '2013-09-01 00:00:00' --train-end '2014-03-31 23:45' --valid-end '2014-05-31 23:45' --test-start '2014-06-01 00:00' --test-end '2014-06-30 23:45'
[ -f results/horizon_risk_IIITD_Library@2014k.json ] || $PY eval/horizon_risk.py --building IIITD_Library --tag @2014k --start '2014-06-01' --end '2014-06-30 23:45' --valid-start '2014-04-01' --valid-end '2014-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Library@2016k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Library --tag @2016k --adaptive-gamma-rel 0.006 --train-start '2015-09-01 00:00:00' --train-end '2016-03-31 23:45' --valid-end '2016-05-31 23:45' --test-start '2016-06-01 00:00' --test-end '2016-06-30 23:45'
[ -f results/horizon_risk_IIITD_Library@2016k.json ] || $PY eval/horizon_risk.py --building IIITD_Library --tag @2016k --start '2016-06-01' --end '2016-06-30 23:45' --valid-start '2016-04-01' --valid-end '2016-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Dining@2017k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Dining --tag @2017k --adaptive-gamma-rel 0.006 --train-start '2016-07-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Dining@2017k.json ] || $PY eval/horizon_risk.py --building IIITD_Dining --tag @2017k --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Facilities@2015k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Facilities --tag @2015k --adaptive-gamma-rel 0.006 --train-start '2014-06-01 00:00:00' --train-end '2015-03-31 23:45' --valid-end '2015-05-31 23:45' --test-start '2015-06-01 00:00' --test-end '2015-06-30 23:45'
[ -f results/horizon_risk_IIITD_Facilities@2015k.json ] || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2015k --start '2015-06-01' --end '2015-06-30 23:45' --valid-start '2015-04-01' --valid-end '2015-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Facilities@2016k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Facilities --tag @2016k --adaptive-gamma-rel 0.006 --train-start '2015-11-01 00:00:00' --train-end '2016-03-31 23:45' --valid-end '2016-05-31 23:45' --test-start '2016-06-01 00:00' --test-end '2016-06-30 23:45'
[ -f results/horizon_risk_IIITD_Facilities@2016k.json ] || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2016k --start '2016-06-01' --end '2016-06-30 23:45' --valid-start '2016-04-01' --valid-end '2016-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Facilities@2017k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Facilities --tag @2017k --adaptive-gamma-rel 0.006 --train-start '2016-01-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Facilities@2017k.json ] || $PY eval/horizon_risk.py --building IIITD_Facilities --tag @2017k --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Boys@2014k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Boys --tag @2014k --adaptive-gamma-rel 0.006 --train-start '2013-09-01 00:00:00' --train-end '2014-03-31 23:45' --valid-end '2014-05-31 23:45' --test-start '2014-06-01 00:00' --test-end '2014-06-30 23:45'
[ -f results/horizon_risk_IIITD_Boys@2014k.json ] || $PY eval/horizon_risk.py --building IIITD_Boys --tag @2014k --start '2014-06-01' --end '2014-06-30 23:45' --valid-start '2014-04-01' --valid-end '2014-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Girls@2014k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Girls --tag @2014k --adaptive-gamma-rel 0.006 --train-start '2013-10-01 00:00:00' --train-end '2014-03-31 23:45' --valid-end '2014-05-31 23:45' --test-start '2014-06-01 00:00' --test-end '2014-06-30 23:45'
[ -f results/horizon_risk_IIITD_Girls@2014k.json ] || $PY eval/horizon_risk.py --building IIITD_Girls --tag @2014k --start '2014-06-01' --end '2014-06-30 23:45' --valid-start '2014-04-01' --valid-end '2014-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Girls@2017k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Girls --tag @2017k --adaptive-gamma-rel 0.006 --train-start '2016-08-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Girls@2017k.json ] || $PY eval/horizon_risk.py --building IIITD_Girls --tag @2017k --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
[ -f models/IIITD_Campus@2017k/forecast_test.parquet ] || $PY forecast/train.py --buildings IIITD_Campus --tag @2017k --adaptive-gamma-rel 0.006 --train-start '2016-08-01 00:00:00' --train-end '2017-03-31 23:45' --valid-end '2017-05-31 23:45' --test-start '2017-06-01 00:00' --test-end '2017-06-30 23:45'
[ -f results/horizon_risk_IIITD_Campus@2017k.json ] || $PY eval/horizon_risk.py --building IIITD_Campus --tag @2017k --start '2017-06-01' --end '2017-06-30 23:45' --valid-start '2017-04-01' --valid-end '2017-05-31 23:45' --skip-closed-loop
echo "kappa arm done $(date)"
